import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "../component/Header.js"
import Footer from "../component/Footer.js"
import PageFooter from "../component/PageFooter.js"
import PageHeader from "@/component/PageHeader";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jakarta.className}>
      <Header />
      <PageHeader />
      <main>{children}</main>
      <PageFooter />
      <Footer />
      </body>
    </html>
  );
}
